# -- 년, 월, 성별 별로 상품 구매한 회원수 집계
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT(I.USER_ID)) AS USERS
FROM USER_INFO I
JOIN ONLINE_SALE O
ON I.USER_ID = O.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER
# SELECT COUNT(USER_ID)
# FROM ONLINE_SALE
# WHERE MONTH(SALES_DATE) = 2