-- 2022년 4월 13일 취소되지 않은 흉부외과 진료 예약 내역
-- 진료예약 일시 기준 오름차순
# SELECT A.APT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD,
#     (SELECT D.DR_NAME 
#     FROM DOCTOR D
#     WHERE A.MDDR_ID = C.DR_ID) AS DR_NAME
#     A.APNT_YMD
# FROM APPOINTMENT A
# JOIN PATIENT P
# ON A.PT_NO = P.PT_NO
# WHERE A.APNT_CNCL_YN = 'N' 
#     # AND YEAR(A.APNT_YMD) = '2022'
#     # AND MONTH(A.APNT_YMD) = '04'
#     # AND DAY(A.APNT_YMD) = '13'
# ORDER BY A.APNT_YMD
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, 
    (SELECT D.DR_NAME 
    FROM DOCTOR D
    WHERE A.MDDR_ID = D.DR_ID) AS DR_NAME,
    A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
WHERE A.APNT_CNCL_YN = 'N' 
    AND YEAR(A.APNT_YMD) = '2022'
    AND MONTH(A.APNT_YMD) = '04'
    AND DAY(A.APNT_YMD) = '13'
ORDER BY A.APNT_YMD